### ISSUE TITLE
Checker doesn't understand magical "objects" member added to Django models

### ISSUE THREAD

**Issue by avengerpenguin** [landscapeio/landscape-issues#1]
I saw this problem with Pylint before where in things like:

https://landscape.io/github/WAFTI/wafti-news/16/modules/news_rhino/views.py

it doesn't understand that the Article model does in fact have an objects member added, but I think it'd done with magical metaclass stuff by Django. As far as static analysis of the class goes, its only members are a set of Django fields, but at runtime it has a lot more going on.

I'm not sure how you work around that apart from maybe having a specific exclusion for Django model classes, which is what I think I've done in that past with pylint (passed in the exclusion as part of the makefile that ran the tests).

**Comment by carlio** [comment]
There is support for this using a pylint plugin I wrote (https://github.com/landscapeio/pylint-django) which provides additional information to the underlying AST parser about 'magical' attributes such as `objects`.

In your case, however, it was not being run as Landscape didn't detect that your project uses Django - it uses [requirements-detector](https://github.com/landscapeio/requirements-detector) under the hood to determine this.

A planned feature is to allow specifying which frameworks are used manually rather than relying on autodetection, to cover the cases where autodetection doesn't work.
