### ISSUE TITLE
Badges shouldn't say "Landscape"

### ISSUE THREAD

**Issue by ssokolow** [landscapeio/landscape-issues#13]
If you look at any of the other badges, you'll see that their invariant portions describe what they're testing, rather than the service's name.

This means that Landscape's badge is flat-out confusing when lined up next to other badges like this:

```
[Build|Passing] [Coverage|100%] [Landscape|100%] [PyPI Package|0.0.1] 
```

"What the heck does "landscape" mean? Is it some technical term I'm unaware of?"

In fact, not only is the inconsistency jarring, when you put "Landscape" up against a bunch of badges which sacrifice the potential to plug their brand in favor of being more clear about what they're measuring, it makes Landscape's badge feel unprofessional by comparison.

The badge should say something like "Metrics" or "Code Quality" instead.

**Comment by carlio** [comment]
I've updated these now - you're right, "Landscape" doesn't immediately mean much. I chose to use 'health' because future features planned for Landscape include checking more things than just code metrics - for example, warning if a repository is missing a license or ensuring that setup.py contains the right amount of information. Eventually it will be 'repository health' rather than just 'code health'.
