### ISSUE TITLE
Prospector execution failed

### ISSUE THREAD

**Issue by resamsel** [landscapeio/landscape-issues#132]
The build fails for https://landscape.io/github/resamsel/dbnavigator/22 (debug), this is what I get:

**Failure reason: Prospector execution failed**

The checking tool, prospector, did not complete correctly

Any idea what I might be doing wrong?

**Comment by carlio** [comment]
Hi @resamsel - seems like you're using tabs instead of spaces in your .landscape.yaml file. It turns out that YAML forbids tabs (see [here](http://www.yaml.org/faq.html)) and that Landscape crashes stupidly if you do. If you convert those tabs to spaces, it will be valid YAML. I'll also convert Landscape so it doesn't die in that case.

**Comment by resamsel** [comment]
Hi @carlio, replacing tabs with 4 spaces does indeed fix the issue, thanks for the quick reply!
