### ISSUE TITLE
Clear documentation needed for running equivalent tests offline prior to pushing

### ISSUE THREAD

**Issue by ssokolow** [landscapeio/landscape-issues#15]
For Landscape.io to be truly useful, the signal-to-noise ratio needs to be high. That means that conscientious, active developers need to be able to run as close to the same set of tests offline before pushing as possible to minimize see-sawing in the Landscape read-out.

Unfortunately, currently, I can't seem to figure out how to match the output of Landscape using an offline Prospector install... it's far too eager to flood me with `C####`-class nonsense about variable names and the like.

To maximize Landscape's success, the documentation needs to be amended with clear, reliable instructions for duplicating Landscape's Prospector configuration.

(While I'd now be concerned about backwards-compatibility when it comes to changing the behaviour used without an explicit config file, the ideal behaviour would be to have a bare "prospector" command give the same "sane, comfortable default" as Landscape under all circumstances.)

**Comment by ssokolow** [comment]
In fact, the simplest solution might just be to offer a script which interprets `.landscape.yaml` and runs Prospector for the user. That way, there'd be no chance of the offline and online settings getting out of sync.

**Comment by carlio** [comment]
1) prospector should match landscape, I agree; it turns out the defaults for both were different, which I have fixed for the next prospector release. For now, `prospector -TD` should give you the same output. (If it doesn't that's likely a bug in Landscape)

2) I feel like I have made a mistake in having two different "tool" names - ideally there'd be a single config file, but having prospector interpret landscape config files, or the other way round, feels a bit like abstraction leak. I think I just have to suck that up, as it were, and instruct users of one to use a filename which doesn't directly make sense.

3) Which repository were you using for the comparison? I'd like to have a look so I can reproduce it myself to figure out if there are any additional differences.

**Comment by ssokolow** [comment]
I was using [ssokolow/quicktile](https://github.com/ssokolow/quicktile/), [ssokolow/gtk-recent-scrubber](https://github.com/ssokolow/gtk-recent-scrubber), and [ssokolow/snakebyte](https://github.com/ssokolow/snakebyte/) and I was getting mismatches with `prospector -DT` and `prospector -DT --path .`

(I tried the latter because someone in another issue mentioned it and I wanted to be thorough)

**Comment by carlio** [comment]
Thanks for this issue report, you helped my find out that Landscape was incorrectly ignoring some errors!

Some new things as a result:

1) Prospector>=0.3.1 now has the same defaults as Landscape, namely, test and documentation warnings are off by default. 

2) Turns out that some of the older way of filtering messages was still in Landscape, so there were two levels of filtering. This is no longer necessary given the strictness profiles in prospector, so I have completely removed the older code. This means that next time you push, some additional messages which were not previously present will show up - sorry about that, they should have been there all along.

3) The 'invalid constant name' which you found has now been moved so that it'll only show up if you set strictness to 'high' or 'veryhigh'

This means that, if you update prospector and have Landscape re-run a check*, simply running 'prospector' in the directory with your code should give the same results as Landscape.

\* This will require a push for now, I'm moving on to implementing #16 soon though

**Comment by ssokolow** [comment]
At the moment, I'm way too busy to give it a try but I'm glad to hear that. :)
