### ISSUE TITLE
Add support/information in relation to missing requirements support

### ISSUE THREAD

**Issue by evilaliv3** [landscapeio/landscape-issues#152]
While working on [GlobaLeaks](https://github.com/globaleaks/GlobaLeaks) i'm noticing that various relevant libraries are missing from landscape but i'm not able to recognise why ad try to solve the issue.

For this libraries as for every condition in which a library is not available it would be interesting to know the reason (eventually exporting the error message).

e.g. for what relates to GlobaLeaks landscape.io is failing to install: cryptography, scrypt, and cyclone.

p.s.: all this libraries are really used among the python communities and it would be valuable to solve the inclusion issue.

![screenshot from 2015-05-06 15 36 49](https://cloud.githubusercontent.com/assets/217034/7494075/dbe6402c-f405-11e4-8fb9-1f6b867a326f.png)

**Comment by carlio** [comment]
Hi @evilaliv3 - this is (apart from occasionaly PyPI downtime) due to not having the correct system library dependencies installed. It's true for things like Pillow and lxml and all things like that. I'm reluctant to solve this by installing the system packages because of the extra compile time required when installing the python packages since it's completely unecessary - just the python code definitions is required. Ideally there would be a `pip install --no-compile` mode or something. I have a vague plan to do something like download the tarball/wheel directly but that sounds like a world of hurt...

**Comment by evilaliv3** [comment]
:( these few innocent libraries

please help us @carlio!! it's a matter of supporting better and in security relevant projects: https://en.wikipedia.org/wiki/GlobaLeaks

**Comment by carlio** [comment]
@evilaliv3 I really want to but installing the system packages and letting pip compile things is really not the right solution for Landscape, it would roughly double or triple the running costs (based on some guestimations) due to the extra running time for each job. It won't be easy to find a workaround but I will definitely try.

**Comment by carlio** [comment]
@evilaliv3 Finally fixed this :)  https://landscape.io/github/globaleaks/GlobaLeaks/1707/requirements
