### ISSUE TITLE
Feature Request: "Synchronise with GitHub" button for individual repositories

### ISSUE THREAD

**Issue by ssokolow** [landscapeio/landscape-issues#16]
As is, Landscape's utility is limited by the long waits for it to realize that a repository has been updated.

That would be solved by fixing up the commit hook and following Travis's example in automating its setup but everything has a hiccup every now so, even then, it would help if the "Synchronise with GitHub" button was also available on individual repository pages to force a check for new commits if a notification got lost along the way.

**Comment by carlio** [comment]
There is a "check for changes now" button on repositories now which will instigate an immediate check for changes.

**Comment by shidarin** [comment]
I cannot for the life of me find the 'check for changes now' button and I would love to, as landscape hasn't picked up any of my changes for the past week :/ Am I just constantly missing it or is the changes button no longer present?

**Comment by carlio** [comment]
@shidarin I recently redesigned everything and it turns out I forgot to include the 'Check now' button. Oops. I'll put that back in place.

Which repositories are not getting changes? I've seen a few cases where the push hook hasn't been correctly set up by Landscape, which could be causing the problem.

**Comment by shidarin** [comment]
I had https://github.com/shidarin/cdl_convert/ tied into it, but the last update it picked up was on the 29th (on a feature branch). Tonight I pushed master and develop branches (release, woo) hoping those would trigger, but no dice.

Before I pushed master & develop, I tried "manually" activating the hook here on github by turning it on.

**Comment by carlio** [comment]
@shidarin I found the problem. It turns out there was a really stupid bug. Landscape would check each branch, but if one had been deleted on GitHub, instead of simply skipping and moving on, it would return from the function early (ie, `return` instead of `continue`). So every time it came to search for new changes it exited immediately. I'm pushing a fix now, hopefully in 5-10 minutes your changes should appear.

**Comment by shidarin** [comment]
Awesome, thanks @carlio , glad it wasn't a big hoo-haa.

**Comment by carlio** [comment]
No worries, thanks for the bug report. It looks like lots of people were affected actually, so it was good to find out! There's now around 100 checks in the queue so it may take a little while before you see the results.

**Comment by carlio** [comment]
There's now a "refresh" icon to force a check of the head of whatever branch you're looking at.
