### ISSUE TITLE
tabs vs spaces

### ISSUE THREAD

**Issue by optimuspaul** [landscapeio/landscape-issues#17]
It's not obvious or possible maybe to say that I prefer tabs to spaces.  Not all of us are mindless sheep who follow the spacer crowd. Some of us actually use logic in our decisions.

**Comment by ssokolow** [comment]
I'm guessing Landscape.io just uses PyLint's default value for `indent-string` which happens to be four spaces because that's what [PEP 8](http://www.python.org/dev/peps/pep-0008/#tabs-or-spaces) says and, while it wasn't intended, PEP 8 has sort of become **the** Python style guide.

I'm not even sure if `pep8.py` (which is on the Landscape.io TODO list of backends) _supports_ overriding that.

**Comment by optimuspaul** [comment]
with pylint you can disable all the silly PEP8 recommendations you want. There are a number that I do by default, this being one of them. PEP 8 has many good points but the recommendation that spaces be used instead of tabs is backward.  Landscape should expose the pep8_ignore options.

**Comment by ssokolow** [comment]
I never said it shouldn't. I was just trying to give some context to anyone who might read this.

(And, to clarify my comment on `pep8.py`, it doesn't really have much customization support beyond an ignores mechanism and what I meant was that I'm not sure whether that's expressive enough to let you explicitly specify tabs as a preferred indenting style to enforce.)

Anyway, now that I've thought about it a bit, for common issues which are also areas of overlap like tabs-vs-spaces, it'd probably make more sense to extend Prospector and expose that new config option in [`.landscape.yaml`](https://landscape.io/pages/docs)  so one config key can control indentation style for both PyLint and `pep8.py`.

**Comment by optimuspaul** [comment]
just adding to the conversation as well.  Pylint covers most if not all of the pep8, does pep8.py duplicate some efforts there?

**Comment by ssokolow** [comment]
I'm honestly not sure. Last time I tried getting PyLint relaxed enough to fit my coding style, I gave up when I discovered pep8.py because PyLint's configuration syntax didn't seem to be expressive enough.

(I had to disable certain PyLint modules entirely because they didn't let me customize their behaviour. However, I don't remember whether the things they checked for were PEP 8 things or things specific to my own coding style.)

As for duplication of effort, that implies certain things about the developers' motivations. If I remember correctly, pep8.py was designed to be a lightweight, "drop in and go" checker suitable for IDEs to support by default while PyLint is more the kind of heavily-opinionated, slower thing you'd want to configure yourself and then run on `git push`.
- pep8.py only cares about style and, if you want fast static analysis in your IDE, you let PyFlakes handle that.
- pep8.py is much lighter and quicker than PyLint so it can be called automatically by IDEs.
- pep8.py comes pre-configured to enforce the common subset of PEP 8 (you need plugins if you want it to complain about the really contentious stuff like "use_underscores(), not camelCase()"
- I could be wrong, but I seem to remember something about older versions of PyLint being prone to import modules the way PyChecker does rather than statically analyzing them like pep8.py and PyFlakes.
- While it's only a couple of extra in-house packages, PyLint still has the most complex dependency tree of any Python analyzer I've seen. That makes it more complicated for a novice user to set up on Windows.

**Comment by optimuspaul** [comment]
lol.. I find PEP 8 to be very opinionated.  My point is pylint covers all of PEP 8, so using both seems extreme. But pylint is also very customizable. I use Sublime Text and it has a plugin for pylint and it's very fast.  We also use it for lints on commits, not as fast because it is more comprehensive and doesn't cache.  But we aren't talking about editors here this is landscape.io, it's processing on commits.  using both pep8.py and pylint is redundantly redundant.  Not having either being configurable is silly, it forces a lot of heavy handed PEP 8 decisions on people. 

Again, not arguing or anything… just adding to the context.

**Comment by carlio** [comment]
I agree that right now Landscape.io is really heavy-handed with "you should use spaces not tabs", and since you get an error per line, it nukes the score for the entire repository which is a bit stupid. My plan is to default to a mode where _consistency_ is enforced (ie, always tabs, or always spaces) and optionally allow people to enforce only tabs/spaces via the config file, if that's their preference. Does that sound sensible to you?

As for the pylint/pep8 debate: currently, Landscape (or rather, [prospector](https://github.com/landscapeio/prospector)) just runs pylint and pep8 is not run at all. Pylint's PEP8 checking is not exactly all of PEP8 - the docs on the [format checker class](https://bitbucket.org/logilab/pylint/src/b9514260964f1ead1714bb4028573043421d0d4e/checkers/format.py?at=default) don't even mention it, because I think pylint predates PEP8. Support for some bits has been added in over time.

Therefore my plan is to disable PEP8-ish checking in pylint and prefer the pep8.py tool, partly because people are likely used to that tool's output and partly because it's a dedicated tool for PEP8 conformity, and I kind of expect it'll be the first of the two tools to reflect the [recent updates to PEP8](http://hg.python.org/peps/rev/fb24c80e9afb). This also makes it easy to disable entirely, should you want to.

**Comment by optimuspaul** [comment]
Yes, very sensible. 

PEP 8 is becoming more and more nazi about the tabs vs spaces debate in my opinion.

**Comment by ssokolow** [comment]
@optimuspaul 
My point is that pep8.py isn't very opinionated over and above the style guide from which it draws its name.

PyLint is not only very strict about logilab's in-house style by default, the default config also has strong opinions on things like whether static methods are allowable (no) and how many attributes you can have on a class (7).

As for PEP 8 becoming more nazi about tabs vs. spaces, could you clarify that? Last I heard, the official position was still "This is a style guide for code in CPython stdlib. If you want to use it outside stdlib, that's your problem."

**Comment by optimuspaul** [comment]
It says it is the style guide for the standard python library. PEP 7 is the style guide for CPython.

The problem is that people are using it as a defense for bad form.  And my point regarding the increasing level of "nazi" is regarding the wording that has been evolving. It went from "Use whichever you want, but we prefer spaces and try not to mix them", then it was "Don't mix tabs and spaces, but we prefer spaces."  Now it's reading more like "only use tabs if you are stuck in the past".  But really the root of it is that so many people say "But PEP 8 says we have to use spaces" when I say use tabs.  They are already using the tab key to indent.  They had to get an editor that would expand tabs to spaces just to support PEP8.  PEP8 is fine in most cases as a style guide.  People need to remember is is just a guide and not hard and fast rules.

Back to pylint, pylint does a lot more than check for style.  In fact in our commit trigger we disable most of the style related checks.  We only care about things that might actually break code.  camelCase isn't going to break code…. at least I hope not.

**Comment by ssokolow** [comment]
Yeah. I tend to use camelCase because it makes it easier to keep things under 80 characters so I can `:vsplit` comfortably.

I do, however, wish pep8.py were smart enough to recognize URLs longer than 79 characters on a single line and apply the 99 character "if it improves readability" limit instead.

**Comment by optimuspaul** [comment]
A related bug is that it says "Mixed indentation" for the warning but I only use tabs.

**Comment by carlio** [comment]
The first part of this has now been completed - choosing the Tab Side no longer means your repository score gets nuked! Landscape will only warn about mixed indentation. 

The configuration option (enforcing tabs or spaces) is something I will open a new issue for.

@optimuspaul I re-ran the check against your code, have a look at https://landscape.io/github/optimuspaul/pymemstore/7

Cheers!
