### ISSUE TITLE
"Recently Checked" on front page should specify which branch was checked

### ISSUE THREAD

**Issue by ssokolow** [landscapeio/landscape-issues#18]
Currently, when checks are displayed for a repository where multiple branches get checked, the displayed result may be misleading.

![2013-12-04-212946_1217x469_scrot](https://f.cloud.github.com/assets/46915/1679611/687ef846-5d56-11e3-8c21-1c82f7ee8ba5.png)

As such, the branch name should be displayed (as it already is in the footer).

![2013-12-04-212957_336x308_scrot](https://f.cloud.github.com/assets/46915/1679612/68fbcf1a-5d56-11e3-8ab3-18c631ffc863.png)

**Comment by carlio** [comment]
I have tweaked this somewhat, but with a different solution, namely that the home page now displays checks from a unique list of repositories. This removes the problem you reported (since there is at most one check from your respository on the home page) but also solves the problem where very active repos were 'drowning out' everything else.
