### ISSUE TITLE
Missing type hinting support

### ISSUE THREAD

**Issue by ranisalt** [landscapeio/landscape-issues#204]
My repository has dropped over 30% in health since I updated it to use type hinting for stricter testing. It should in fact issue a higher health rate as code can be safer with hints.

Here's the line causing the failure: https://landscape.io/github/ranisalt/moita/22/messages/error?page=1#errors

The entire file is now 0% health. Support for hinting was included in Python 3.5 and does not change syntax neither functionality, it is merely for testing purposes.

**Comment by carlio** [comment]
@ranisalt This was due to Landscape not supporting Python 3, but I have added Python 3 support in the last few days. The problem now is that the default assumption is still Python 2. You can make Landscape use 3 by either adding trove classifiers in your setup.py indicating what versions you support, and/or adding a Landscape configuration file:

More info in the docs here: https://docs.landscape.io/configuration.html#python-targets-2-3

Cheers!

**Comment by ranisalt** [comment]
Thanx! Worked like a charm, plus now I have a 100% health badge hahahah
