### ISSUE TITLE
Landscape falsely notifies about circular imports

### ISSUE THREAD

**Issue by schumannd** [landscapeio/landscape-issues#214]
Landscape lists non-existent circular imports in files that were not even touched. These get listed under both allegedly new problems and fixed problems.

So neither is this circular import correct, nor that it has been fixed or introduced.

Example: https://landscape.io/diff/279743

**Comment by karyon** [comment]
to be more precise, the circular imports do exist, but they are in the wrong place, but this is an issue of pylint itself, see https://github.com/PyCQA/pylint/issues/59.

an actual issue of landscape is that it reports these imports as "fixed" and "new" at the same time in every single report on every single pull request. see the example linked by @schumannd. this made me disable the warning completely because having "3 new problems were found" and "3 problems were fixed" in every pull request is not helpful :)

**Comment by mathuin** [comment]
I just created #264 which may be related to this issue.  Any help on where to find these alleged cyclic imports would be appreciated. :-)
