### ISSUE TITLE
Service doesn't work most of the time. What's going on?

### ISSUE THREAD

**Issue by mistercrunch** [landscapeio/landscape-issues#231]
The service is not picking up tasks. Our PRs depend on it. 
https://github.com/airbnb/caravel/pulls

**Comment by carlio** [comment]
@mistercrunch Finally managed to track down what was happening here, sorry it took so long. It turns out the tasks were running just fine, but it was not able to update the PR status due to using the token of a user who does not appear to have write access to the repositories, only pull access. Not sure why this changed only recently but it's fixed on Landscape now to make sure it only picks users who have write access. Please reopen if you notice any other issues with this but it is working again now, and I've set it to go through and properly update the PR statuses.

**Comment by mistercrunch** [comment]
@carlio I still have this issue where pretty often, as a result PR are stuck in a "brown" state. I'm really getting close to getting rid of the service altogether as it gets in the way.

Look at the PRs in a brown state here:
https://github.com/airbnb/caravel/pulls

**Comment by carlio** [comment]
@mistercrunch I'll look into it now

**Comment by carlio** [comment]
@mistercrunch Found the issue, turns out one of the checkers got stuck in a zombie state so half of the checks were just waiting. I've fixed this, and in a short time your checks and PRs should be back up to date. Sorry about that! I'll set up some better monitoring for checkers getting stuck like this.
