### ISSUE TITLE
Pull request scan stopped working

### ISSUE THREAD

**Issue by petricm** [landscapeio/landscape-issues#232]
We (https://github.com/DIRACGrid/DIRAC) have for some time successfully used the pull request scan option of landscape e.g.:

https://github.com/DIRACGrid/DIRAC/pull/2939
https://github.com/DIRACGrid/DIRAC/pull/2941

however since 25th May the feature does not anymore work for us. It works only if the scan is triggered by hand. 

https://landscape.io/github/DIRACGrid/DIRAC

How can we reactivate this option?

CC: @atsareg, @fstagni, @andresailer

**Comment by carlio** [comment]
Hi @petricm . I checked into this and it seems like the push hook wasn't installed on the repository. Not sure why yet, I didn't get any errors through. Usually if that happens, Landscape falls back on polling the API but that hasn't been happening for a few hours due to some workers failing. I've restarted them, so you may see it start up again, and I'll figure out why the push hook wasn't working.

**Comment by petricm** [comment]
Dear @carlio thank you for looking into this matter. However I have made a new PR after you restarted but I don't see any landscape response https://github.com/DIRACGrid/DIRAC/pull/2989

**Comment by carlio** [comment]
@petricm I finally started to figure this out. It turns out that organisations have "admin", "write" and "read" access that now seems to limit which users can grant third-party apps the ability to create hooks. I will look into making it so that Landscape picks someone from the organisation who has the required access. I think this is relatively new, I've never noticed this before.

In the mean time you have two options: 1) you can manually add the hook yourself in your repository settings page, 2) you can wait a bit until I fix this (hopefully won't take long now I understand the bug) or 3) wait for the polling to kick in, not sure why it's being so slow but that'll be what I get on to next.

**Comment by carlio** [comment]
@petricm never mind - fixed the hook creation now so it shoud Just Work™ for you now!

**Comment by petricm** [comment]
Dear @carlio thank you again for your help. After another push to https://github.com/DIRACGrid/DIRAC/pull/2989 landscape did indeed pick up the push. However it seems at the moment that it is stuck, 2h have passed and no report. Also the details link in the PR does not point to the specific analysis.  There was also another PR to our repo (https://github.com/DIRACGrid/DIRAC/pull/2990), after you fixed landscape, but it also exhibits the same behavior.

**Comment by carlio** [comment]
@petricm thanks for the testing. I think this is a different issue now, which is also happening here: https://github.com/landscapeio/landscape-issues/issues/231
- looking into it!

**Comment by carlio** [comment]
@petricm turns out this was a similar problem actually (see also this comment https://github.com/landscapeio/landscape-issues/issues/231#issuecomment-226735606) - both hook creation and PR status updates seem to have changed required permissions recently and I didn't know this yet. Should be fixed now, please let me know if you notice further issues but I think it's working.

**Comment by petricm** [comment]
Dear @carlio thank you for fixing it. I just have one more question. Why are there no notifications to the conversation of the PR from landscape like before (https://github.com/DIRACGrid/DIRAC/pull/2993). We used to receive a report from landscape similar the one from coveralls indicating this PR fixed X errors and introduced Y new erros ... Thank you again.

**Comment by carlio** [comment]
@petricm fixed that too now! The bot was running behind since all the PRs only just got updated.

**Comment by petricm** [comment]
Dear @carlio somehow we got a report into this PR https://github.com/DIRACGrid/DIRAC/pull/2990, but the test one I opened did not receive any report https://github.com/DIRACGrid/DIRAC/pull/2995

**Comment by petricm** [comment]
Also any subsequent PRs https://github.com/DIRACGrid/DIRAC/pull/2997 don't get a report.

**Comment by petricm** [comment]
Hi @carlio , please re-open this issue, the scan reports still don't get delivered into the PR conversation.

**Comment by kosack** [comment]
I have the same problem with https://landscape.io/github/cta-observatory/ctapipe/pulls/  - the PRs worked fine for a while, then stopped suddenly, with only  a status of "Comparsion did not run" or "Checks currently running" (which never completes, and no status is given)
