### ISSUE TITLE
Prospector execution failed

### ISSUE THREAD

**Issue by hhslepicka** [landscapeio/landscape-issues#234]
Hi, 
I have been facing this error after adding a couple of lines to my ignore-paths.
I would like to know if there is a way to check if something is wrong in my code that is generating this error.

Here is the url for the code: https://github.com/hhslepicka/conftrak

```
Check number 63 has failed. This is almost always due to a bug in Landscape - we have been notified. Sorry about that.

Failure reason: Prospector execution failed

The checking tool, prospector, did not complete correctly
```

Thanks!

**Comment by carlio** [comment]
@hhslepicka I was looking into this earlier, turns out there's a bug in prospector. You specify 'targets' in .landscape.yml with 2.7 but it only accepts 2 or 3 (the actual version is not important it's just a generic 2 vs 3 question) and it turns out that breaks things. I added a fix to prospector here: https://github.com/landscapeio/prospector/commit/d7bb629ab35797b850db6f49f3844a930377d422  and will make a release soon to include it in Landscape. For now you could change 2.7 to 2 to get Landscape working again, or wait a bit until I get the code all updated. Sorry!

**Comment by hhslepicka** [comment]
Thanks @carlio ! This completely solved the issue! Congratulations on the amazing tool that you developed! 💯  👍
