### ISSUE TITLE
Landscape fails with "Prospector execution failed"

### ISSUE THREAD

**Issue by grzanka** [landscapeio/landscape-issues#243]
Repository under consideration: https://landscape.io/github/DataMedSci/pymchelper/72

I cannot even repeat the job.

Check number 72 has failed. This is almost always due to a bug in Landscape - we have been notified. Sorry about that.

Failure reason: Prospector execution failed

The checking tool, prospector, did not complete correctly

**Comment by lewismc** [comment]
I have a very similar issue... different check number though.

![screen shot 2016-08-17 at 7 26 24 pm](https://cloud.githubusercontent.com/assets/1165719/17759795/7b76d2e4-64af-11e6-8377-9eb7340b6401.png)

**Comment by carlio** [comment]
@lewismc Something just happened to all the checkers, investigating now!

**Comment by carlio** [comment]
@lewismc Figured this out - turns out your .landscape.yml file has slightly invalid syntax which causes prospector to die (yes that is stupid it should be better at this!) This line needs to be `full: true` (note the extra space): https://github.com/lewismc/podaacpy/blob/master/.landscape.yml#L25

I'll work on making this more resiliant to parse failures, it really shouldn't just completely give up like this.

@grzanka I'll close this as I think the checks are working now, please re-open if not!

**Comment by lewismc** [comment]
Thanks very much. Great help. :+1:
