### ISSUE TITLE
Server Error 500

### ISSUE THREAD

**Issue by CJ-Wright** [landscapeio/landscape-issues#260]
I a Server Error 500 for this PR https://landscape.io/github/xpdAcq/redsky/pulls/1
Any thoughts on what might be going on?

**Comment by carlio** [comment]
I had a look, this seems like a bit of a silly one really - it's because that repository has no python files in it. Obviously it shouldn't raise a 500 server error in that case, I'll look into making it handle the situation better.

**Comment by CJ-Wright** [comment]
That would be fair but the PR has python code in it: https://github.com/CJ-Wright/redsky/blob/e535286b9cca952c4428ffd2aef5b64ef0d024b7/redsky/analysis_run_engine.py
I am assuming that landscape is looking at the PR code.

**Comment by robin-miller-ow** [comment]
I am also having this issue on the following PR: https://landscape.io/github/owlabs/incubator-airflow/pulls/16

I was wondering if this might be a knock-on effect of checks being unable to run successfully on one of the branches since the latest commit: https://landscape.io/github/owlabs/incubator-airflow/180 (I have re-run the check several times with the same failure result.)

**Comment by bowenli86** [comment]
Having this problem too. 
https://landscape.io/github/apache/incubator-airflow/pulls/1926    shows server error 500.

This is silly.

**Comment by skudriashev** [comment]
Guys, any updates on this?
