### ISSUE TITLE
Landscape not acknowledging fast-forward merge

### ISSUE THREAD

**Issue by ssokolow** [landscapeio/landscape-issues#287]
I just came back to working on [this project](https://landscape.io/github/ssokolow/quicktile) and, while Landscape did check the commits I made to the `multiple_files` branch, it still shows the score for the main branch as it was before those commits were fast-forward merged. (99% when it should be 95% from being dragged down by `gtkexcepthook.py`.)

(Specifically, it's still acting as if check 56 corresponds to `HEAD` rather than check 69.)

**Comment by lafrech** [comment]
I'm afraid I'm facing the same issue.

I have a few recent commits in there:
https://github.com/Nobatek/flask-rest-api/commits/master

But landscape seems still stuck in September:
https://landscape.io/github/Nobatek/flask-rest-api/

Looks like I configured it wrong, but I can't tell what the problem is.
