### ISSUE TITLE
Landscape needs a documented way to set global PyLint rules

### ISSUE THREAD

**Issue by ssokolow** [landscapeio/landscape-issues#56]
It feel as if every other line in my D-Bus code consists of the comment

```
# pylint: disable=bad-continuation
```

...because the only human-readable alternative would be to make ridiculously long lines, rely on word-wrap, and leverage Landscape's support for shutting up PyFlakes instead.

**Comment by pennyarcade** [comment]
:+1:  :)
If you're looking for a ".landscape.yaml" in the root dir why not look for a ".pylintrc" in the format "pylint --generate-rcfile" gives you. This makes it really easy for users to get started.
(I already have one for my shippable.com builds)

That shouldn't be hard to implement since you already have the infrastructure there and you only have to hand it to pylint as is.

You can expand this pattern without much inconvenience for the other tools. Only (small) drawback I see is that you will end up with 3-5 config files in your projects root for landscape alone plus some more for other services.
I already have 4 :)

**Comment by carlio** [comment]
Finally sorted out a proper documentation site: https://docs.landscape.io/suppressing.html

if a `.pyintrc` exists it will be used by Prospector (and I should document that better)
