### ISSUE TITLE
Landscape tests more than 10 commits and 2 days behind

### ISSUE THREAD

**Issue by pennyarcade** [landscapeio/landscape-issues#57]
Hello,

Landscape wasn't running any tests this weekend although there were more than 10 commits pushed.

My setup:
- My main repository is at Bitbucket.
- I am using shippable.com to run unittests and some code analysis
- Shippable pushes numbered commits to my Github repository i solely set up for landscape
- Landscape runs off my github repository

Last commit on Github:
- [skip ci] shippable build 180 (e29767d88b55f8ffc5d5647c8c7a4d998e6786ca)
- Jul 06, 2014, evening

Last Landscape run
- [skip ci] shippable build 170 
- 5 Jul 2014, 1:11 p.m.

Please have a look, landscape is at the moment not giving any advantage over my old semi-manual code quality monitoring.

**Comment by pennyarcade** [comment]
Somehow the Landscape Service was missing in my Github repository. I didn't delete it.
Readding it manually to the repository does not seem to work, I have been waiting for an hour for a new run to appear. I really hate loosing my test history but it seems I'll have to remove the repository from landscape and try to add it in again. :-(

**Comment by pennyarcade** [comment]
Removing the repository from being checked and adding it again didn't help either.

**Comment by pennyarcade** [comment]
Deleting my whole account does not work either. I am quite frustrated.

**Comment by pennyarcade** [comment]
Latest run #113 worked :)

**Comment by carlio** [comment]
This was fixed by a change in prospector: https://github.com/landscapeio/prospector/commit/6d51a1492b081f490df62411549f94c87085862c

Honestly, I don't quite understand how this didn't break a long time ago! Essentially, modules which were not in a package (ie, a directory not including an `__init__.py` file) were not added to the path, which caused imports to break. This is now fixed in the underlying tool.
