### ISSUE TITLE
Feature Request: language-neutral backend

### ISSUE THREAD

**Issue by caiobegotti** [landscapeio/landscape-issues#7]
Really, your site looks amazing it has a GREAT potential! That's exactly what I've been looking for these days because I really need a mentor to tell me what's wrong and what should I do with my code so it looks decent. That said, maybe you could also somehow check against Android code using their lints etc. You already import mixed-languages projects anyway. Now, "android java code supported" would be totally hot for people. I know a lot of folks who would use it more with Java than Python, though I'm a Python guy myself and don't know Java, so...

**Comment by carlio** [comment]
Adding other languages would be a huge undertaking, because I would need to find and understand the relevant tools for those languages. I'd love to figure out how to have PHP support in there, for example, and maybe some day I can devote time to that once I nail the Python analysis.

For now, check out http://www.sonarqube.org/ for Java code analysis :)

**Comment by Fuchida** [comment]
It would be better to do one thing very well, Python code analysis.
