### ISSUE TITLE
100% health when it's not

### ISSUE THREAD

**Issue by hugovk** [landscapeio/landscape-issues#70]
Landscape reports a repo's health is 100% with defaults.

I added a .landscape.yaml config file and did a build to include warnings for tests, and then increased strictness from default medium to high and very high but all four still got 100% health.

https://landscape.io/github/hugovk/Pillow/24

I'm quite certain this shouldn't be the case because Travis CI is also running PEP8 and Pyflakes at the end of the build and gives plenty of warnings. For example:

https://travis-ci.org/hugovk/Pillow/jobs/34919670#L2787

And Landscape seems to know about the files. listing all 233 .py files:

https://landscape.io/github/hugovk/Pillow/24/modules?classes=syntax&classes=error&classes=smell&classes=style&classes=docs&show_all=all

Do I have the config somehow wrong?

Thanks!

**Comment by carlio** [comment]
I had a look, it turns out this is a combination of bugs. The problem is firstly that [frosted](https://github.com/timothycrosley/frosted) is failing to handle the "Häggström" in (https://github.com/hugovk/Pillow/blob/master/PIL/WalImageFile.py) due to some kind of encoding issue which I haven't figured out yet. Landscape should detect that failure but does not, which is the second part of the bug.

I will dig into it more and submit a bug report for frosted once I figure out what's wrong. Hopefully I can also patch or workaround it enough to get the check running correctly.

If you want to get some accurate scores from Landscape in the meantime, then you could add something to your `.landscape.yaml`:

```
ignore-files:
  PIL/WalImageFile.py
```

This is obviously a hack and I will update you when I get a real solution!

**Comment by hugovk** [comment]
Thanks for investigating.

I've added the workaround, but still get 100% and the file still shows up in the list of all files. Some things I tried:

```
ignore-files:
  PIL/WalImageFile.py
```

There's no `ignore-files` in the docs, but there is `ignore-dirs` and `ignore-patterns`. 

```
ignore-patterns:
    - PIL/WalImageFile.py
```

```
ignore-patterns:
    - PIL/WalImageFile.py$
```

(It might be worth adding an `ignore-files` to avoid possible unwanted matches with `ignore-patterns`.)

**Comment by hugovk** [comment]
@carlio So how can a file be ignored by Landscape?

I see this didn't work in your test either; it still reports 100% health and zero warnings: 

```
test-warnings: yes
strictness: veryhigh
ignore-files:
  - PIL/WalImageFile.py
```

https://landscape.io/github/carlio/Pillow/3

**Comment by carlio** [comment]
Hi @hugovk I haven't forgotten about this, just been super busy the last few days! It turns out there's a further bug in `prospector` in which `frosted` was not correctly ignoring files, and as such there isn't a way to get frosted to ignore this file. I have a workaround in prospector which I want to test and release soon, and once I update Landscape with that new release hopefully things will work a bit better.

(see https://github.com/landscapeio/prospector/commit/081ee98a2b89b47682381cf3a23dc5a30b99dfa7)

**Comment by carlio** [comment]
@hugovk This [commit to prospector](https://github.com/landscapeio/prospector/commit/d43e88cb1ba32fe9f34a40d77340c7d27aa04c95) has mitigated the problem, so that now 1) the ignoring configuration works properly and 2) if `frosted` fails due to an encoding error, it is simply skipped for that file, as `pyflakes` will flag most of the same issues.

You should be able to remove that `ignore-files` config too, if you like.

The score is now working properly - see https://landscape.io/github/hugovk/Pillow/69

Sorry it took so long, it was a combination of about 4 bugs in 4 different projects!

**Comment by hugovk** [comment]
@carlio Thanks for the fixes, happy to have helped identify four bugs in four projects!
