### ISSUE TITLE
Unused variables smells twice

### ISSUE THREAD

**Issue by hayd** [landscapeio/landscape-issues#72]
For the line:

```
bzr_log = shell_out(["bzr", "log"])
```

the (same) smell is reported twice under a slightly different guise:

```
Unused variable 'bzr_log'
# and
local variable 'bzr_log' is assigned to but never used
```

see https://landscape.io/github/hayd/pep8radius/4/messages/smell.

_Personally/Aside I don't think there's harm in this "smell", and I ~~think it's~~ thought it was reasonable to want descriptive as I occasionally want to access it's value when debugging (since the function is not pure it may be different when called again)._

**Comment by carlio** [comment]
The fix for this is now in Landscape, you can see in this file that there is now just one single warning for the unused `bzr_log` and similar: https://landscape.io/github/hayd/pep8radius/49/modules/pep8radius/vcs.py

As for your aside: there are plans to allow much more nuanced ability to turn on or off the various errors and warnings, it will happen eventually I promise!
