### ISSUE TITLE
Can I set a prospector profile file for my repo?

### ISSUE THREAD

**Issue by dreispt** [landscapeio/landscape-issues#83]
From the docs, we can see that we can create a `.landscape.yaml` configuration file for our repos.
But what about `prospector` profiles?
I would like to tune what specific checks pep8 and pylint should perform.

**Comment by carlio** [comment]
If you have a `.prospector.yaml` in the root of your repository, it will get used. This is an accidental feature at the moment though, so there's no documentation about it. I do intend to figure out a good way to do this in the future.

**Comment by dreispt** [comment]
Thanks for the answer.

Leaving that as is sounds good.
Even better would be for the .landscape.yaml to also fit that purpose. Maybe by using it as prospector profile after stripping out landscape specific entries.

**Comment by carlio** [comment]
That's the plan - I don't want Prospector and Landscape to require different configuration files. It's just on the TODO list rather than the TODONE list.

**Comment by cdeil** [comment]
So if both `.prospector.yaml` and `.landscape.yaml` are present, how are they combined?

For people that want to run `prospector` locally as well as on `landscape`, is the recommendation to _only_ put a `.prospector.yaml`, or are there options that need to go in `.landscape.yaml`?

Documenting this, even if it's just one sentence at https://landscape.io/pages/docs pointing to http://prospector.readthedocs.org/en/latest/profiles.html#profiles would be great.

**Comment by carlio** [comment]
@cdeil "So if both .prospector.yaml and .landscape.yaml are present, how are they combined?"

This is something I'm trying to figure out. I think I made a mistake right at the beginning by naming the commandline tool differently. My current plan would be to change things so that `.landscape.yml` and `.prospector.yml` are basically the same thing, so that both tools can use both. That way only one is required. Basically it's a bit of a mess right now due to a decision made a long time ago!

**Comment by carlio** [comment]
Finally clarified this: https://docs.landscape.io/configuration.html

Basically, prospector and landscape configuration files are equivalent.
