### ISSUE TITLE
Badges are cached by GitHub

### ISSUE THREAD

**Issue by Bjwebb** [landscapeio/landscape-issues#89]
(when included on README pages etc.)

This issue suggests it's to do with how GitHub responds to caching headers:
https://github.com/github/markup/issues/224

**Comment by carlio** [comment]
Ooooohhhhhh. I have been wondering about this for aaages. I set "Cache-Control: max-age=0" and it wasn't working, and never got around to figuring out why. Turns out it means a slightly different thing to 'no-cache' - http://stackoverflow.com/questions/1046966/whats-the-difference-between-cache-control-max-age-0-and-no-cache

Thanks for the link, that was really helpful. I've made the change and will monitor over the next few days to see if this isn't a problem any more.

**Comment by teleyinex** [comment]
The badges are still cached ;-) It shows in my project 86% of health while in your home page is 91% :D

**Comment by carlio** [comment]
Bah. Then their documentation is all lies!

**Comment by carlio** [comment]
Finally figured this out btw. It turns out that shields.io sets 'cache for a day' headers when using the generic API (as Landscape does) but sets 'cache never' for badges that are prime citizens. This means that either Landscape serves SVG badges itself, or creates a pull request for the shields repo.

**Comment by teleyinex** [comment]
:+1:

**Comment by carlio** [comment]
Landscape is now serving the SVG badges itself. At a later date I'll add Landscape into shields.io as a first-class citizen but for now the generic API doesn't really work.

Once the GitHub cache clears out, this should be working properly.
