### ISSUE TITLE
Bug: Committer link on project page is broken.

### ISSUE THREAD

**Issue by jnovinger** [landscapeio/landscape-issues#9]
Similar to #8, the link applied to the last committer's name is broken.

Expected: https://github.com/davidbgk
Actual: https://github.com/David%20Larlet

Screenshot: 
![landscape hosted continuous python code metrics - google chrome_475](https://f.cloud.github.com/assets/103499/1545850/94e1b584-4d7c-11e3-8d46-3711df34a079.png)

**Comment by ssokolow** [comment]
When fixing that, also keep in mind committers who aren't paired with GitHub accounts.

...or, for that matter, committers who _can't_ be paired. My commit string used to be claimed but, when GitHub started requiring `user.email` to be a valid e-mail address (rather than the URL to a contact form which I use to prevent spam), I just decided I'd continue committing as-is and let my commits stay unclaimed.

**Comment by carlio** [comment]
I tried to fix this but, as @ssokolow says, it's not as easy as a 1-1 mapping, and actually the new UI doesn't include the link. I will close this as "no longer a problem".

(Feel free to open an issue if you feel the link would be useful)
