### ISSUE TITLE
Can not install lxml

### ISSUE THREAD

**Issue by nijel** [landscapeio/landscape-issues#90]
I've noticed that some projects depend on lxml and fail to install it. This could be fixed by installing libxml2-dev and libxslt-dev packages on the build host.

Examples:
https://landscape.io/github/nijel/weblate/3731/requirements
https://landscape.io/github/fsr-itse/EvaP/143/requirements

**Comment by carlio** [comment]
Hi @nijel , this is definitely something I want to fix, and pretty much any Python package which requires a system package has the same problem. However I don't really want to just install the relevant system packages then have the python package compile every time Landscape runs - this would make each check much slower and it's already a bit slow. I'm looking for a way to install a package without needing to compile native bindings, because the python endpoints are the only bits needed for inference.

**Comment by carlio** [comment]
I'm going to close this because at this point in time there is no good solution.
