### ISSUE TITLE
Add support for specifying dependencies in ``.landscape.yml``

### ISSUE THREAD

**Issue by astrofrog** [landscapeio/landscape-issues#96]
It would be nice to have a way to specify dependencies in the `.landscape.yml` file directly. I tried doing:

```
uses:
    - numpy
    - matplotlib
```

but then realized that this is not what `uses` is intended for (it only supports `django` and `celery`). Why now allow e.g.:

```
dependencies:
    - numpy
    - matplotlib
```

?

cc @cdeil

**Comment by cdeil** [comment]
This would be great!

It would also be nice to have some documentation on what actually happens for the dependencies listed in `requirements.txt` on `landscape.io` ... e.g. if `numpy` or `matplotlib` are dependencies how do they enter the `pylint` static analysis of my package?

A few more sentences here about what's going on would be great!
https://landscape.io/pages/faq#how-does-it-work

**Comment by carlio** [comment]
@cdeil I will update the documentation and FAQ, Landscape has evolved a bit since it was originally written.

The short version is that Landscape uses [requirements-detector](https://github.com/landscapeio/requirements-detector) to find the project dependencies, which includes parsing `setup.py`. When parsing `setup.py` however, it only considers `install_requires` not `requires`. This is an oversight, I didn't realise there was a `requires` option! I will add that to requirements-detector and create a new release over the next day or two, and that will work its way into Landscape. I'll update this issue when it's done.

**Comment by carlio** [comment]
(See also https://github.com/landscapeio/requirements-detector/issues/3)
